### ISSUE TITLE
Varying layer parameters per layer within a part

### ISSUE THREAD

**Issue by engblaze** [VanHulleOne/SciSlice#4]
Hi there!

I stumbled on SciSlice when looking for AM g-code generation tools that give more fine-grained control over the extrusion process, and it looks awesome. However, I noticed that when slicing a part with multiple layers, the set layer parameters appear to apply for all layers - i.e. if I set an infill angle of 45deg, all n layers will have the same infill angle. What I'd really like to do is customize (either algorithmically or manually) the layer params per layer, i.e. infill angle of 0deg for layer 1, 10deg for layer 2, etc. Is there a recommended way to do this out of the box with SciSlice? Or would it involve making modifications to the way Figura is invoked when g code is requested?

Thanks!

**Comment by VanHulleOne** [comment]
Parameters that are set as `layer parameters` can be changed with each layer of the part. By default, the infill angle is a layer parameter. To change it just enter a list of values in the infill angle field (comma or space separated) and that list will be cycled through until the number of layers is reached. Its been a while since I have actually used this project but I know it works for predefined shapes and I am pretty sure it works properly for STLs.

**Comment by engblaze** [comment]
Ah, I didn't realize you could input lists for the layer properties. Perfect, thank you! I tried on a few sample STLs and it seems to work just fine.

Would it be useful to submit a pull request to make the documentation a bit clearer on that point? Or if you're no longer actively maintaining the project, no worries. Either way, thanks for sharing your great work and for the quick response!

**Comment by VanHulleOne** [comment]
I can make the time to merge in a pull request if you think you've got some improvements for the documentation. It's always nice to have some user perspective in a user manual.
